// <auto-generated />
namespace PackageBD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modify_tpack_entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_tpack_entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201708020730248_modify_tpack_entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
